apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: amqps
      port: 15675
      targetPort: 15675
