apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-mqtt-consumer
spec:
  selector:
    app: rabbitmq-mqtt-consumer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
