apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management
          ports:
            - containerPort: 5672   # AMQP
            - containerPort: 15672  # RabbitMQ Management UI
            - containerPort: 1883   # MQTT
            - containerPort: 15675  # Web MQTT
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-storage
          command: ["/bin/bash", "-c"]
          args:
            - |
              rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt &&
              rabbitmq-server
      volumes:
        - name: rabbitmq-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: web-mqtt
      protocol: TCP
      port: 15675
      targetPort: 15675
  type: LoadBalancer  
